In [5]:
import numpy as np
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms': [3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor': [5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks': [8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})


   1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40


In [12]:
# 1.7.1 Найдите вектор параметров квартиры номер 5
A = Hut_Paradise_DF.values
y = A[4]  # 4 строка матрицы
print(y)


[40 33  1  6 20 16]


In [13]:
# 1.7.2 Найдите вектор этажей всех квартир
floors = A[:, 3]  
print(floors)


[ 5 12 10  3  6 13  8 21  5]


In [14]:
# 1.7.3 На каком этаже расположена квартира номер 3
print(floors[2])


10


In [17]:
# 1.7.4 Найдите количество квартир
print(len(floors))


9


In [21]:
# 1.7.5 Вычислите вектор нежилой площади
areas = A[:, 1]
las = A[:, 5]
print(areas - las)


[13 12 15 13 17  9 20 15 25]


In [25]:
# 1.7.6 Пересчитайте стоимость аренды каждой квартиры в гривны, если курс 10 руб = 4 гривны
rent = A[:, 0]
print(0.4 * rent)


[26. 28. 48. 14. 16. 20. 40. 36. 34.]


In [29]:
# 1.7.7 Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели
views = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
demos = A[:, 4]
print(np.sum(views * demos))


1348


In [31]:
# 1.7.8 Составьте линейную комбинацию векторов  с коэффициентами 2 и -3
u = np.array([3, 0, 1, 1, 1])
v = np.array([0, 1, 0, 2, -2])
w = np.array([1, -4, -1, 0, -2])
vw = 2*v + -3*w
print(vw)


[-3 14  3  4  2]


In [32]:
# 1.7.9 комбинация ортогональна вектору?
print('(u,vw):', u@vw)


(u,vw): 0


In [35]:
# 1.7.10 Нормируйте векторы
u_norm = u / np.linalg.norm(u)
print('u_norm:', u_norm)

v_norm = v / np.linalg.norm(v)
print('v_norm:', v_norm)

w_norm = w / np.linalg.norm(w)
print('w_norm:', w_norm)


u_norm: [0.8660254  0.         0.28867513 0.28867513 0.28867513]
v_norm: [ 0.          0.33333333  0.          0.66666667 -0.66666667]
w_norm: [ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]
